/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelo.AsignarEsp;
import Modelo.LLenarCombo;
import Modelo.Medico;
import ModeloMedico.Tabla;
import Vistas.JFprincipal;
import java.awt.event.KeyEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author CRISTIAN
 */
public class AsignarEspecialidad extends javax.swing.JDialog {
DefaultTableModel tablaEspecialidad = new DefaultTableModel();
    /**
     * Creates new form AsignarEspecialidad
     */
    public AsignarEspecialidad(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(880, 400);
        this.setTitle("Especialidad");
        sbus.requestFocus();
        String titulo[]= {"ID_DOCTOR", "NOMBRE", "APELLIDO"};
        tablaEspecialidad = new DefaultTableModel( titulo,0);
        Tespecialidad.setModel(tablaEspecialidad);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BUSCAR = new javax.swing.JButton();
        EDITAR = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        sape = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        scod = new javax.swing.JTextField();
        snom = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        sbus = new javax.swing.JTextField();
        Combo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tespecialidad = new javax.swing.JTable();
        btnVolver = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Asignar Especialidad:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(345, 11, 127, 14);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 117, 47, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Especialidad:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 234, 72, 14);

        BUSCAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.jpg"))); // NOI18N
        BUSCAR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUSCARActionPerformed(evt);
            }
        });
        BUSCAR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BUSCARKeyPressed(evt);
            }
        });
        getContentPane().add(BUSCAR);
        BUSCAR.setBounds(607, 66, 36, 23);

        EDITAR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EDITAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Editar.jpg"))); // NOI18N
        EDITAR.setText("Asignar");
        EDITAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDITARActionPerformed(evt);
            }
        });
        EDITAR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EDITARKeyPressed(evt);
            }
        });
        getContentPane().add(EDITAR);
        EDITAR.setBounds(140, 310, 130, 25);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Nueva Especialidad");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(680, 70, 150, 23);

        sape.setEnabled(false);
        sape.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sapeKeyPressed(evt);
            }
        });
        getContentPane().add(sape);
        sape.setBounds(82, 172, 177, 20);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Código:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 69, 41, 14);

        scod.setEnabled(false);
        scod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                scodKeyPressed(evt);
            }
        });
        getContentPane().add(scod);
        scod.setBounds(82, 66, 177, 20);

        snom.setEnabled(false);
        snom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                snomKeyPressed(evt);
            }
        });
        getContentPane().add(snom);
        snom.setBounds(82, 114, 177, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Apellido:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(329, 70, 56, 14);

        sbus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sbusKeyPressed(evt);
            }
        });
        getContentPane().add(sbus);
        sbus.setBounds(395, 67, 206, 20);

        Combo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Combo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ComboMousePressed(evt);
            }
        });
        Combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboActionPerformed(evt);
            }
        });
        Combo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ComboKeyPressed(evt);
            }
        });
        getContentPane().add(Combo);
        Combo.setBounds(82, 231, 177, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Apellido:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 175, 48, 14);

        Tespecialidad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Tespecialidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        Tespecialidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TespecialidadMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tespecialidad);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(329, 100, 508, 255);

        btnVolver.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Regresar.jpg"))); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver);
        btnVolver.setBounds(20, 310, 99, 23);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salud1.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 870, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUSCARActionPerformed
        Medico m = new Medico(); 
        m.BuscarMedico(sbus.getText(), tablaEspecialidad);   
        LLenarCombo llenar = new LLenarCombo();
        Tabla tabla = new Tabla();
        llenar.LimpiarCombo(Combo);
        llenar.Presentar(Combo);
        
        
    }//GEN-LAST:event_BUSCARActionPerformed

    private void EDITARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDITARActionPerformed
      AsignarEsp asignar = new AsignarEsp();
      String especialidad =Combo.getSelectedItem().toString();
      JOptionPane.showMessageDialog(null, asignar.AsignarEspecialidad(scod.getText(),especialidad ) );
      
      sbus.requestFocus();
      scod.setText("");
      snom.setText("");
      sape.setText("");
      sbus.setText("");
    }//GEN-LAST:event_EDITARActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JDagEspecialidad agg = new JDagEspecialidad (new JFprincipal(), true); 
        agg.setLocationRelativeTo(null);
        agg.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TespecialidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TespecialidadMouseClicked
        DefaultTableModel modelo = (DefaultTableModel) Tespecialidad.getModel();
       scod.setText(modelo.getValueAt(Tespecialidad.getSelectedRow(),0)+""); 
       snom.setText(modelo.getValueAt(Tespecialidad.getSelectedRow(),1)+"");
       sape.setText(modelo.getValueAt(Tespecialidad.getSelectedRow(),2)+"");
       snom.setEnabled(true);
       sape.setEnabled(true);
       scod.setEnabled(false);
    }//GEN-LAST:event_TespecialidadMouseClicked

    private void ComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboActionPerformed
        
    }//GEN-LAST:event_ComboActionPerformed

    private void ComboMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboMousePressed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void sbusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sbusKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            BUSCAR.requestFocus();
        }
    }//GEN-LAST:event_sbusKeyPressed

    private void BUSCARKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BUSCARKeyPressed
        // TODO add your handling code here:
        String buscar = sbus.getText();
        if(buscar.length()==0)
        {
            JOptionPane.showMessageDialog(null, "Para realizar una busqueda el registro no puede estar vacio", "Advertencia", JOptionPane.WARNING_MESSAGE);
            sbus.requestFocus();
        }
        else
        {
            if(buscar.length()>50)
            {
                JOptionPane.showMessageDialog(null, "El numero de caracteres ingresados no pueden ser mayor a 50", "Advertencia", JOptionPane.WARNING_MESSAGE);
                sbus.requestFocus();
   
            }
            else
            {
                Medico m = new Medico(); 
                m.BuscarMedico(sbus.getText(), tablaEspecialidad);   
                LLenarCombo llenar = new LLenarCombo();
                Tabla tabla = new Tabla();
                llenar.LimpiarCombo(Combo);
                llenar.Presentar(Combo);
            }
        }
    }//GEN-LAST:event_BUSCARKeyPressed

    private void scodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_scodKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            snom.requestFocus();
        }
    }//GEN-LAST:event_scodKeyPressed

    private void snomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_snomKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            sape.requestFocus();
        }
    }//GEN-LAST:event_snomKeyPressed

    private void sapeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sapeKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            Combo.requestFocus();
        }
    }//GEN-LAST:event_sapeKeyPressed

    private void ComboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ComboKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            EDITAR.requestFocus();
        }
    }//GEN-LAST:event_ComboKeyPressed

    private void EDITARKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EDITARKeyPressed
        // TODO add your handling code here:ç
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            AsignarEsp asignar = new AsignarEsp();
            String especialidad =Combo.getSelectedItem().toString();
            Icon i = new ImageIcon(getClass().getResource("/Imagenes/Aceptar.jpg"));
            JOptionPane.showMessageDialog(null, asignar.AsignarEspecialidad(scod.getText(),especialidad ),"Mensaje",JOptionPane.INFORMATION_MESSAGE, i );
            sbus.requestFocus();
        }
    }//GEN-LAST:event_EDITARKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsignarEspecialidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsignarEspecialidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsignarEspecialidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsignarEspecialidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AsignarEspecialidad dialog = new AsignarEspecialidad(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BUSCAR;
    public static javax.swing.JComboBox<String> Combo;
    private javax.swing.JButton EDITAR;
    private javax.swing.JTable Tespecialidad;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField sape;
    private javax.swing.JTextField sbus;
    private javax.swing.JTextField scod;
    private javax.swing.JTextField snom;
    // End of variables declaration//GEN-END:variables
}
