/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelo.AsignarEsp;
import Modelo.LLenarCombo;
import java.awt.event.KeyEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author CRISTIAN
 */
public class JDagEspecialidad extends javax.swing.JDialog {

    /**
     * Creates new form JDagEspecialidad
     */
    public JDagEspecialidad(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(380, 230);
        this.setTitle("Nueva Especialidad");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cc = new javax.swing.JTextField();
        ee = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Agregar Especialidad No Existente");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 20, 250, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("ESPECIALIDAD:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(18, 113, 84, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("CÓDIGO ESPECIALIDAD:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 74, 140, 20);

        cc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ccKeyPressed(evt);
            }
        });
        getContentPane().add(cc);
        cc.setBounds(148, 73, 168, 20);

        ee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                eeKeyPressed(evt);
            }
        });
        getContentPane().add(ee);
        ee.setBounds(148, 110, 168, 20);

        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AgregarBoton.jpg"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        btnAgregar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAgregarKeyPressed(evt);
            }
        });
        getContentPane().add(btnAgregar);
        btnAgregar.setBounds(132, 159, 100, 25);

        btnVolver.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnVolver.setText("Cancelar");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver);
        btnVolver.setBounds(232, 159, 90, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salud2.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 370, 200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        AsignarEsp asignar = new AsignarEsp();
        JOptionPane.showMessageDialog(null,asignar.AgregarEspecialidad(cc.getText(), ee.getText()));
        LLenarCombo llenar = new LLenarCombo();
        llenar.LimpiarCombo(AsignarEspecialidad.Combo);
        llenar.Presentar(AsignarEspecialidad.Combo);
        cc.setText("");
        ee.setText("");
        this.hide();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void ccKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ccKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            ee.requestFocus();
        }
    }//GEN-LAST:event_ccKeyPressed

    private void eeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eeKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            btnAgregar.requestFocus();
        }
    }//GEN-LAST:event_eeKeyPressed

    private void btnAgregarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAgregarKeyPressed
        // TODO add your handling code here:
        String cc = this.cc.getText();
        String ee = this.ee.getText();
        if(cc.length()==0||ee.length()==0)
        {
            JOptionPane.showMessageDialog(null, "Los registros no pueden estar vacios\nPor favor llene los registros", "Advertencia", JOptionPane.WARNING_MESSAGE);
            this.cc.requestFocus();
        }
        else
        {
            if(cc.length()>50||ee.length()>50)
            {
                JOptionPane.showMessageDialog(null, "El numero de caracteres permitido es de 50", "Advertencia", JOptionPane.WARNING_MESSAGE);
                this.cc.requestFocus();
            }
            else
            {
                AsignarEsp asignar = new AsignarEsp();
                Icon i = new ImageIcon(getClass().getResource("/Imagenes/Aceptar.jpg"));
                JOptionPane.showMessageDialog(null,asignar.AgregarEspecialidad(this.cc.getText(), this.ee.getText()),"Mensaje",JOptionPane.INFORMATION_MESSAGE, i);
                LLenarCombo llenar = new LLenarCombo();
                llenar.LimpiarCombo(AsignarEspecialidad.Combo);
                llenar.Presentar(AsignarEspecialidad.Combo);
                this.hide();
            }
        }
    }//GEN-LAST:event_btnAgregarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDagEspecialidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDagEspecialidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDagEspecialidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDagEspecialidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDagEspecialidad dialog = new JDagEspecialidad(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JTextField cc;
    private javax.swing.JTextField ee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
