/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelo.Cita;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sun.security.util.Length;

/**
 *
 * @author Admin
 */
public class JDAgregarCita extends javax.swing.JDialog {

    /**
     * Creates new form JDAgregarVisita
     */
               
    //-------------creacion de la variable tipo tabla para PACIENTES-----------
    
    DefaultTableModel modeloPacientes;
    
    //---------------------------------------------------------- 
  
    
    
    public JDAgregarCita(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        //--------------inicializacion del disenio de la tabla----------------
        modeloPacientes = new DefaultTableModel(); //le asignamos todas las funciones al modelo
        jtPaciente.setModel(modeloPacientes); //le asignamos a la tabla el modelo que creamos
        String Titulos1[] = { "Apellidos", "Nombre", "Direccion", "Telefono"}; //creamos una variable con el nombre que queremos para la tabla
        modeloPacientes.setColumnIdentifiers(Titulos1); //le asignamos al modelo el nombre que creamos en la linea anterior
        //------------------------------------------------------------------- 

        //---------------------para que al ejecutar esta clase liste de una vez los doctores actuales--------------------------
        Cita nuevoListar = new Cita();
        nuevoListar.ColocarDoctoresCBX(cbxDoctores);
        //---------------------------------------------------------------------------------------------------------------------
       
        
        //--------para que siempre aparescan ocultos los txt de los id----------
        txtIdPaciente.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPaciente = new javax.swing.JTable();
        txtApelPaciente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JDTfecha = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        txtIdPaciente = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        cbxDoctores = new javax.swing.JComboBox<>();
        btnRegresar1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("AGREGAR UNA CITA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Apellidos del Paciente: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 76, -1, -1));

        jtPaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Apellidos", "Nombre", "Direccion", "Telefono"
            }
        ));
        jScrollPane1.setViewportView(jtPaciente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 117, 544, 65));

        txtApelPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtApelPacienteKeyPressed(evt);
            }
        });
        getContentPane().add(txtApelPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 79, 183, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Seleccione un Doctor:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Fecha:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 327, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Hora:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 327, -1, -1));
        getContentPane().add(JDTfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 327, 156, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton1.setText("AGREGAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 380, 213, 46));
        getContentPane().add(txtIdPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 79, 90, -1));
        getContentPane().add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 330, 117, -1));

        getContentPane().add(cbxDoctores, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 226, 183, 35));

        btnRegresar1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRegresar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Regresar.jpg"))); // NOI18N
        btnRegresar1.setText("Volver");
        btnRegresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 461, 100, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/OMS3.1.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 420, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(txtIdPaciente.getText().length()==0 || JDTfecha.getDate()==null || txtHora.getText().length()==0) //validacion para saber si los campos estan vacios
        {                                                                                    //observar que para el JDate si es igual a null es que esta vacio
            JOptionPane.showMessageDialog(null, "ERROR: Complete la informacion requerida");
        }
        else //si no estan vacios
        {
           if(Integer.parseInt(txtHora.getText())>=1 && Integer.parseInt(txtHora.getText())<=24) //validamos si la hora es aceptable
           {
                //asignacion de los datos a una variable tipo fecha
                Date fecha = JDTfecha.getDate();
                
                //creacion de un formato de fecha que se quiera objtener
                SimpleDateFormat formato = new SimpleDateFormat("d/MM/yyyy");


                Cita nuevaCita = new Cita();
                nuevaCita.BuscarIdDoctor(Integer.parseInt(txtIdPaciente.getText()), formato.format(fecha), Integer.parseInt(txtHora.getText()), cbxDoctores.getSelectedItem().toString(), modeloPacientes);
                        //enviamos los dato                la fcha se envia con el formato creado antes
                        //                                                              la hora la pasamos a int, la parseamos    
                        
                        
                    //LA LIMPIEZA DE LOS TXT QUEDO EN EL METODO DE VALIDACION    

           }
           else //si no es aceptable
           {
               JOptionPane.showMessageDialog(null, "EROR: porfavor ingrese una hora aceptable (entre 1 y 24 hrs)");
           }
        }
        
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtApelPacienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApelPacienteKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)// para que cuando reciva un ENTER haga lo siguiente
        {
            Cita nuevaBusqueda = new Cita();
            nuevaBusqueda.BuscarPaciente(txtApelPaciente.getText(), modeloPacientes);
        }         
        
    }//GEN-LAST:event_txtApelPacienteKeyPressed

    private void btnRegresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnRegresar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDAgregarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDAgregarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDAgregarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDAgregarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDAgregarCita dialog = new JDAgregarCita(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static com.toedter.calendar.JDateChooser JDTfecha;
    private javax.swing.JButton btnRegresar1;
    private javax.swing.JComboBox<String> cbxDoctores;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jtPaciente;
    public static javax.swing.JTextField txtApelPaciente;
    public static javax.swing.JTextField txtHora;
    public static javax.swing.JTextField txtIdPaciente;
    // End of variables declaration//GEN-END:variables
}
