/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vistas;

import Modelo.Medico;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CRISTIAN
 */
public class JDbuscar extends javax.swing.JDialog {
DefaultTableModel tabla = new DefaultTableModel();
    /** Creates new form JDbuscar */
    public JDbuscar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(640, 270);
        this.setTitle("Buscar");
        bApellido.requestFocus();
        String titulo[]= {"ID_DOCTOR", "NOMBRE", "APELLIDO","DIRECCIÓN", "TELÉFONO","COLEGIADO"};
        tabla = new DefaultTableModel( titulo,0);
        tablita.setModel(tabla);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bApellido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablita = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("AR JULIAN", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("BUSCAR MéDICO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 10, 240, 28);

        bApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bApellidoKeyPressed(evt);
            }
        });
        getContentPane().add(bApellido);
        bApellido.setBounds(10, 87, 108, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Apellido:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(38, 55, 60, 14);

        tablita.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tablita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tablita.setEnabled(false);
        jScrollPane1.setViewportView(tablita);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(166, 55, 452, 159);

        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.jpg"))); // NOI18N
        btnBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        btnBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnBuscarKeyPressed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(120, 80, 30, 30);

        btnRegresar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Regresar.jpg"))); // NOI18N
        btnRegresar.setText("Volver");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar);
        btnRegresar.setBounds(10, 130, 100, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salud4.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 40, 630, 230);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(150, 30, 10, 190);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("LIMPIAR TABLA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(430, 20, 160, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String apellido = bApellido.getText();
        if(apellido.length()==0)
        {
            JOptionPane.showMessageDialog(null, "Para realizar una busqueda, el registro debe estar lleno", "Advertencia", JOptionPane.WARNING_MESSAGE);
            bApellido.requestFocus();
        }
        else
        {
            if(apellido.length()>50)
            {
                JOptionPane.showMessageDialog(null, "El apellido no puede ser mayor a 50 caracteres", "Advertencia", JOptionPane.WARNING_MESSAGE);
                bApellido.requestFocus();
            }
            else
            {
             Medico med =new  Medico(); 
             med.BuscarMedico(bApellido.getText(), tabla);
             btnBuscar.setText("");
             btnBuscar.requestFocus();
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void bApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bApellidoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            btnBuscar.requestFocus();
        }
    }//GEN-LAST:event_bApellidoKeyPressed

    private void btnBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnBuscarKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            String apellido = bApellido.getText();
        if(apellido.length()==0)
        {
            JOptionPane.showMessageDialog(null, "Para realizar una busqueda, el registro debe estar lleno", "Advertencia", JOptionPane.WARNING_MESSAGE);
            bApellido.requestFocus();
        }
        else
        {
            if(apellido.length()>50)
            {
                JOptionPane.showMessageDialog(null, "El apellido no pued ser mayor a 50 caracteres", "Advertencia", JOptionPane.WARNING_MESSAGE);
                bApellido.requestFocus();
            }
            else
            {
             Medico med =new  Medico(); 
             med.BuscarMedico(bApellido.getText(), tabla);
             bApellido.requestFocus();
            }
        }
        }
    }//GEN-LAST:event_btnBuscarKeyPressed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Medico limpiar = new Medico();
        limpiar.Limpiar(tabla);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDbuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDbuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDbuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDbuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDbuscar dialog = new JDbuscar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bApellido;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tablita;
    // End of variables declaration//GEN-END:variables

}
