/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelo.Cita;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class JDEditarCita extends javax.swing.JDialog {

    /**
     * Creates new form JDEditarCita
     */
    
    //-------------creacion de la variable tipo tabla para PACIENTES-----------
    
    DefaultTableModel modeloCitasEditar;
    
    //----------------------------------------------------------        
    
    
    public JDEditarCita(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        //--------------inicializacion del disenio de la tabla----------------
        modeloCitasEditar = new DefaultTableModel(); //le asignamos todas las funciones al modelo
        jtCitasEditar.setModel(modeloCitasEditar); //le asignamos a la tabla el modelo que creamos
        String Titulos1[] = {"No." ,"Apellidos Paciente", "Nombre Paciente", "Hora de la Cita"}; //creamos una variable con el nombre que queremos para la tabla
        modeloCitasEditar.setColumnIdentifiers(Titulos1); //le asignamos al modelo el nombre que creamos en la linea anterior
        //-------------------------------------------------------------------         
        
        //---------------------para que al ejecutar esta clase liste de una vez los doctores actuales--------------------------
        Cita nuevoListar = new Cita();
        nuevoListar.ColocarDoctoresCBX(cbxDoctoresEditar);
        
        nuevoListar.ColocarDoctoresCBX(cbxDoctoresNuevoEditar); //tambien para el combobox que servirar para los nuevos datos
        //---------------------------------------------------------------------------------------------------------------------  
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbxDoctoresEditar = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtCitasEditar = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jdFechaEditar = new com.toedter.calendar.JDateChooser();
        txtHoraEditar = new javax.swing.JTextField();
        txtApellidosPacienteEdit = new javax.swing.JTextField();
        cbxDoctoresNuevoEditar = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        JDFechaCitaEditar = new com.toedter.calendar.JDateChooser();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("EDITAR UNA CITA");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Seleccione un Doctor:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Fecha:");

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton1.setText("BUSCAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jtCitasEditar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No.", "Apellidos Paciente", "Nombre Paciente", "Hora de la cita"
            }
        ));
        jtCitasEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtCitasEditarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtCitasEditarMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtCitasEditarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jtCitasEditarMouseReleased(evt);
            }
        });
        jtCitasEditar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtCitasEditarKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jtCitasEditar);

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setText("EDITAR CITA SELECCIONADA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton3.setText("ATRAS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Apellidos Paciente:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Seleccione el nuevo Doctor: ");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Nueva Fecha:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Nueva Hora:");

        txtApellidosPacienteEdit.setFocusable(false);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 204));
        jLabel9.setText("Ingreso de los Nuevos Datos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(cbxDoctoresNuevoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jdFechaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtHoraEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApellidosPacienteEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(29, 29, 29)
                                .addComponent(JDFechaCitaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(31, 31, 31)
                                .addComponent(cbxDoctoresEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel9)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxDoctoresEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(JDFechaCitaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtApellidosPacienteEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbxDoctoresNuevoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(txtHoraEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jdFechaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(JDFechaCitaEditar.getDate()==null)//si no se ingreso una fecha 
        {
            JOptionPane.showMessageDialog(null, "ERROR: ingrese una fecha para buscar las citas");
            
            //solo para limpiar la tabla 
            Cita nuevaLimpieza = new Cita();
            nuevaLimpieza.limpiarTabla(modeloCitasEditar);            
        }
        else //si ya ingreso una fecha 
        {
            //asignacion de los datos a una variable tipo fecha
            Date fecha = JDFechaCitaEditar.getDate();
              
            //creacion de un formato de fecha que se quiera objtener
            SimpleDateFormat formato = new SimpleDateFormat("d/MM/yyyy");            
            
            
            Cita nuevaBusqueda = new Cita();//creamos un objeto 
            nuevaBusqueda.BuscarCitaDoc(cbxDoctoresEditar.getSelectedItem().toString(), formato.format(fecha), modeloCitasEditar);  //enviamos los parametros requeridos
                            //ojo que para obtener el dado seleccionado del combobox es diferente            
        }        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        if(JDFechaCitaEditar.getDate()==null || jdFechaEditar.getDate()==null || txtApellidosPacienteEdit.getText().length()==0 || txtHoraEditar.getText().length()==0) //validacion para saber si los campos estan vacios
        {                                                                                    //observar que para el JDate si es igual a null es que esta vacio
            JOptionPane.showMessageDialog(null, "ERROR: Complete la informacion requerida");
        }        
        else
        {
           if(Integer.parseInt(txtHoraEditar.getText())>=1 && Integer.parseInt(txtHoraEditar.getText())<=24) //validamos si la hora es aceptable
           {    
                //asignacion de los datos a una variable tipo fecha
                Date fecha = jdFechaEditar.getDate();

                //asignacion de los datos a una variable tipo fecha
                Date fecha2 = JDFechaCitaEditar.getDate();                
                
                //creacion de un formato de fecha que se quiera objtener
                SimpleDateFormat formato = new SimpleDateFormat("d/MM/yyyy");


              
            
                Cita nuevaCita = new Cita();
                nuevaCita.BuscarIdsEditar(txtApellidosPacienteEdit.getText(), formato.format(fecha), Integer.parseInt(txtHoraEditar.getText()), cbxDoctoresNuevoEditar.getSelectedItem().toString(), modeloCitasEditar,jtCitasEditar, formato.format(fecha2), cbxDoctoresEditar.getSelectedItem().toString());
                        //enviamos los dato                la fcha se envia con el formato creado antes
                        //                                                              la hora la pasamos a int, la parseamos

                //nuevaCita.datosFilaSeleccionadaEditar(jTable1, modeloCitasEditar, txtFechaCitaEditar.getText() , cbxDoctoresEditar.getSelectedItem().toString());               
           }   
           else //si no es aceptable
           {
               JOptionPane.showMessageDialog(null, "EROR: porfavor ingrese una hora aceptable (entre 1 y 24 hrs)");
           }           
        }
        
                        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtCitasEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtCitasEditarMouseClicked
        // TODO add your handling code here:
            
        //esto es para asignarle un valor al textfield al hacer un clic 
        txtApellidosPacienteEdit.setText(modeloCitasEditar.getValueAt(jtCitasEditar.getSelectedRow(), 1)+"");
                    //             obtenemos valores del modelo creado          le decimos que obtenga el valor seleccionado de la fila 
                                                    //recordar que la tabla es como un vector que empieza desde 0
    }//GEN-LAST:event_jtCitasEditarMouseClicked

    private void jtCitasEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtCitasEditarMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtCitasEditarMouseEntered

    private void jtCitasEditarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtCitasEditarMousePressed
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_jtCitasEditarMousePressed

    private void jtCitasEditarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtCitasEditarMouseReleased
        // TODO add your handling code here:
             
    }//GEN-LAST:event_jtCitasEditarMouseReleased

    private void jtCitasEditarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCitasEditarKeyPressed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_jtCitasEditarKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDEditarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDEditarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDEditarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDEditarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDEditarCita dialog = new JDEditarCita(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static com.toedter.calendar.JDateChooser JDFechaCitaEditar;
    private javax.swing.JComboBox<String> cbxDoctoresEditar;
    private javax.swing.JComboBox<String> cbxDoctoresNuevoEditar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    public static com.toedter.calendar.JDateChooser jdFechaEditar;
    private javax.swing.JTable jtCitasEditar;
    public static javax.swing.JTextField txtApellidosPacienteEdit;
    public static javax.swing.JTextField txtHoraEditar;
    // End of variables declaration//GEN-END:variables
}
