/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelo.Medico;
import ModeloMedico.Tabla;
import java.awt.event.KeyEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CRISTIAN
 */
public class JDEditar extends javax.swing.JFrame {
DefaultTableModel tablaE = new DefaultTableModel();
    /**
     * Creates new form JDeditar
     */
    public JDEditar() {
        initComponents();
        setSize(867, 450);
        this.setTitle("Editar");
         Inhabilitar();
         String titulo[]= {"ID_DOCTOR", "NOMBRE", "APELLIDO","DIRECCIÓN", "TELÉFONO","COLEGIADO"};
        tablaE = new DefaultTableModel( titulo,0);
        tablaEditar.setModel(tablaE);
    }

    
    
    public void Inhabilitar()
    {
        this.eCodigo.setEnabled(false);
        this.eNombre.setEnabled(false);
        this.eApellido.setEnabled(false);
        this.eDireccion.setEnabled(false);
        this.eTelefono.setEnabled(false);
        this.eColegiado.setEnabled(false);
    }
    
    public void Habilitar()
    {
        this.eCodigo.setEnabled(false);
        this.eNombre.setEnabled(true);
        this.eApellido.setEnabled(true);
        this.eDireccion.setEnabled(true);
        this.eTelefono.setEnabled(true);
        this.eColegiado.setEnabled(true);
        this.eNombre.requestFocus();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enviar = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        eApellido = new javax.swing.JTextField();
        eDireccion = new javax.swing.JTextField();
        eTelefono = new javax.swing.JTextField();
        eNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        buscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEditar = new javax.swing.JTable();
        BUSCAR = new javax.swing.JButton();
        EDITAR = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        eCodigo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        eColegiado = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnVolver = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        enviar.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("AR JULIAN", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setText("Editar Medico");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 260, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 117, 50, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Apellido:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 172, 60, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Dirección:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 237, 60, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Teléfono:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 303, 60, 14);

        eApellido.setEnabled(false);
        eApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                eApellidoKeyPressed(evt);
            }
        });
        getContentPane().add(eApellido);
        eApellido.setBounds(85, 169, 177, 20);

        eDireccion.setEnabled(false);
        eDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                eDireccionKeyPressed(evt);
            }
        });
        getContentPane().add(eDireccion);
        eDireccion.setBounds(85, 234, 177, 20);

        eTelefono.setEnabled(false);
        eTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                eTelefonoKeyPressed(evt);
            }
        });
        getContentPane().add(eTelefono);
        eTelefono.setBounds(85, 300, 177, 20);

        eNombre.setEnabled(false);
        eNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                eNombreKeyPressed(evt);
            }
        });
        getContentPane().add(eNombre);
        eNombre.setBounds(85, 114, 177, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Apellido:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(297, 80, 70, 14);

        buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscarKeyPressed(evt);
            }
        });
        getContentPane().add(buscar);
        buscar.setBounds(371, 77, 206, 20);

        tablaEditar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tablaEditar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tablaEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEditarMouseClicked(evt);
            }
        });
        tablaEditar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablaEditarKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tablaEditarKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(tablaEditar);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(291, 117, 524, 253);

        BUSCAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.jpg"))); // NOI18N
        BUSCAR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUSCARActionPerformed(evt);
            }
        });
        BUSCAR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BUSCARKeyPressed(evt);
            }
        });
        getContentPane().add(BUSCAR);
        BUSCAR.setBounds(590, 70, 30, 29);

        EDITAR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EDITAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Editar.jpg"))); // NOI18N
        EDITAR.setText("Editar");
        EDITAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDITARActionPerformed(evt);
            }
        });
        EDITAR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EDITARKeyPressed(evt);
            }
        });
        getContentPane().add(EDITAR);
        EDITAR.setBounds(130, 370, 110, 23);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Listar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(730, 80, 80, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Código:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 69, 50, 14);

        eCodigo.setEnabled(false);
        eCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                eCodigoKeyPressed(evt);
            }
        });
        getContentPane().add(eCodigo);
        eCodigo.setBounds(85, 66, 177, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("No. Colegiado:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(1, 346, 80, 14);

        eColegiado.setEnabled(false);
        getContentPane().add(eColegiado);
        eColegiado.setBounds(85, 340, 177, 20);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(279, 0, 2, 410);

        btnVolver.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Regresar.jpg"))); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver);
        btnVolver.setBounds(30, 370, 90, 23);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salud6.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 850, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEditarMouseClicked
       DefaultTableModel modelo = (DefaultTableModel) tablaEditar.getModel();
       eCodigo.setText(modelo.getValueAt(tablaEditar.getSelectedRow(),0)+""); 
       eNombre.setText(modelo.getValueAt(tablaEditar.getSelectedRow(),1)+"");
       eApellido.setText(modelo.getValueAt(tablaEditar.getSelectedRow(),2)+"");
       eDireccion.setText(modelo.getValueAt(tablaEditar.getSelectedRow(),3)+"");
       eTelefono.setText(modelo.getValueAt(tablaEditar.getSelectedRow(),4)+"");
       eColegiado.setText(modelo.getValueAt(tablaEditar.getSelectedRow(),5)+"");
       eCodigo.setEnabled(false);
       eColegiado.setEnabled(false);
       Habilitar();

    }//GEN-LAST:event_tablaEditarMouseClicked

    private void tablaEditarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaEditarKeyPressed
        
    }//GEN-LAST:event_tablaEditarKeyPressed

    private void tablaEditarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaEditarKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaEditarKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Medico m = new Medico(); 
        Tabla t = new Tabla();
        t.LimpiarTabla(tablaE);
        m.PresentarDatos(tablaE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUSCARActionPerformed
        String buscar = this.buscar.getText();
        if(buscar.length()==0)
        {
            JOptionPane.showMessageDialog(null, "El registro no puede estar vacio", "Advertencia", JOptionPane.WARNING_MESSAGE);
            this.buscar.requestFocus();
        }
        else
        {
            if(buscar.length()>50)
            {
            JOptionPane.showMessageDialog(null, "El apellido o nombre no puede ser mayor a 50 caracteres", "Advertencia", JOptionPane.WARNING_MESSAGE);
            this.buscar.requestFocus();
            }
            else
            {
                Medico m = new Medico(); 
                m.BuscarMedico(this.buscar.getText(), tablaE);
                Inhabilitar();
            }
        }
    }//GEN-LAST:event_BUSCARActionPerformed

    private void EDITARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDITARActionPerformed
        Medico emedico = new Medico( eApellido.getText(), eNombre.getText(), eDireccion.getText(), eTelefono.getText(), eColegiado.getText());
        JOptionPane.showMessageDialog(null, emedico.EditarMedico(emedico, eCodigo.getText()));
        Tabla t = new Tabla();
        t.LimpiarTabla(tablaE);
        emedico.PresentarDatos(tablaE);
        eApellido.setText("");
        eCodigo.setText("");
        eNombre.setText("");
        eDireccion.setText("");
        eTelefono.setText("");
        eColegiado.setText("");
        buscar.setText("");
        
    }//GEN-LAST:event_EDITARActionPerformed

    private void eCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eCodigoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            eNombre.requestFocus();
        }
    }//GEN-LAST:event_eCodigoKeyPressed

    private void eNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eNombreKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            eApellido.requestFocus();
        }
    }//GEN-LAST:event_eNombreKeyPressed

    private void eApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eApellidoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            eDireccion.requestFocus();
        }
    }//GEN-LAST:event_eApellidoKeyPressed

    private void eDireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eDireccionKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            eTelefono.requestFocus();
        }
    }//GEN-LAST:event_eDireccionKeyPressed

    private void eTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eTelefonoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            EDITAR.requestFocus();
        }
    }//GEN-LAST:event_eTelefonoKeyPressed

    private void EDITARKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EDITARKeyPressed
        // TODO add your handling code here:
        String codigo = eCodigo.getText();
        String apellido = eApellido.getText();
        String nombre = eNombre.getText();
        String direccion = eDireccion.getText();
        String telefono = eTelefono.getText();
        String colegiado = eColegiado.getText();
        if(codigo.length()==0||apellido.length()==0||nombre.length()==0||direccion.length()==0||telefono.length()==0||colegiado.length()==0)
        {
            JOptionPane.showMessageDialog(null, "Los registros no pueden estar vacios\nPor favor llene los registros", "Advertencia", JOptionPane.WARNING_MESSAGE);
            eNombre.requestFocus();
        }
        else
        {
            if(apellido.length()>50||nombre.length()>50||direccion.length()>50||telefono.length()>12||colegiado.length()>50)
            {
                JOptionPane.showMessageDialog(null, "El numero de caracteres en los registros es mayor al permitido\nNombre, Apellido, Direccion y Colegiado no pueden ser mayor a 50 caracteres\nTelefono no puede ser mayor a 12", "Advertencia", JOptionPane.WARNING_MESSAGE);
                eNombre.requestFocus();
            }
            else
            {
                Icon i = new ImageIcon(getClass().getResource("/Imagenes/Aceptar.jpg"));
                Medico emedico = new Medico( eApellido.getText(), eNombre.getText(), eDireccion.getText(), eTelefono.getText(), eColegiado.getText());
                JOptionPane.showMessageDialog(null, emedico.EditarMedico(emedico, eCodigo.getText()),"Mensake",JOptionPane.INFORMATION_MESSAGE, i);
                Tabla t = new Tabla();
                t.LimpiarTabla(tablaE);
                emedico.PresentarDatos(tablaE);
                eNombre.requestFocus();
            }
        }
    }//GEN-LAST:event_EDITARKeyPressed

    private void buscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            BUSCAR.requestFocus();
        }
    }//GEN-LAST:event_buscarKeyPressed

    private void BUSCARKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BUSCARKeyPressed
        // TODO add your handling code here:
        String codigo = eCodigo.getText();
        String apellido = eApellido.getText();
        String nombre = eNombre.getText();
        String direccion = eDireccion.getText();
        String telefono = eTelefono.getText();
        String colegiado = eColegiado.getText();
        if(codigo.length()==0||apellido.length()==0||nombre.length()==0||direccion.length()==0||telefono.length()==0||colegiado.length()==0)
        {
            JOptionPane.showMessageDialog(null, "Los registros no pueden estar vacios\nPor favor llene los registros", "Advertencia", JOptionPane.WARNING_MESSAGE);
            eNombre.requestFocus();
        }
        else
        {
            if(apellido.length()>50||nombre.length()>50||direccion.length()>50||telefono.length()>12||colegiado.length()>50)
            {
                JOptionPane.showMessageDialog(null, "El numero de caracteres en los registros es mayor al permitido\nNombre, Apellido, Direccion y Colegiado no pueden ser mayor a 50 caracteres\nTelefono no puede ser mayor a 12", "Advertencia", JOptionPane.WARNING_MESSAGE);
                eNombre.requestFocus();
            }
            else
            {
                Icon i = new ImageIcon(getClass().getResource("/Imagenes/Aceptar.jpg"));
                Medico emedico = new Medico( eApellido.getText(), eNombre.getText(), eDireccion.getText(), eTelefono.getText(), eColegiado.getText());
                JOptionPane.showMessageDialog(null, emedico.EditarMedico(emedico, eCodigo.getText()),"Mensaje",JOptionPane.INFORMATION_MESSAGE, i);
                Tabla t = new Tabla();
                t.LimpiarTabla(tablaE);
                emedico.PresentarDatos(tablaE);
                eNombre.requestFocus();
            }
        }
    }//GEN-LAST:event_BUSCARKeyPressed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JDEditar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BUSCAR;
    private javax.swing.JButton EDITAR;
    private javax.swing.JButton btnVolver;
    private javax.swing.JTextField buscar;
    private javax.swing.JTextField eApellido;
    private javax.swing.JTextField eCodigo;
    private javax.swing.JTextField eColegiado;
    private javax.swing.JTextField eDireccion;
    private javax.swing.JTextField eNombre;
    private javax.swing.JTextField eTelefono;
    private javax.swing.JMenuItem enviar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tablaEditar;
    // End of variables declaration//GEN-END:variables
}
