/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelo.Medico;
import ModeloMedico.Tabla;
import java.awt.event.KeyEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CRISTIAN
 */
public class JDeliminar extends javax.swing.JDialog {
DefaultTableModel tablaEli = new DefaultTableModel();
Integer accion = 1;
    /**
     * Creates new form JDeliminar
     */
    public JDeliminar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(840, 500);
        this.setTitle("Eliminar");
        Inhabilitar();
        String titulo[]= {"ID_DOCTOR", "NOMBRE", "APELLIDO","DIRECCIÓN", "TELÉFONO","Colegiado"};
        tablaEli = new DefaultTableModel( titulo,0);
        tablaeliminar.setModel(tablaEli);
    }
    
    public void Inhabilitar()
    {
        this.ecod.setEnabled(false);
        this.enom.setEnabled(false);
        this.eape.setEnabled(false);
        this.edir.setEnabled(false);
        this.etel.setEnabled(false);
        this.ecole.setEnabled(false);
    }
    
    public void Habilitar()
    {
        this.ecod.setEnabled(false);
        this.enom.setEnabled(true);
        this.eape.setEnabled(true);
        this.edir.setEnabled(true);
        this.etel.setEnabled(true);
        this.ecole.setEnabled(true);
        this.enom.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        aux = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaeliminar = new javax.swing.JTable();
        busqueda = new javax.swing.JButton();
        lista = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        enom = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        eape = new javax.swing.JTextField();
        edir = new javax.swing.JTextField();
        ecod = new javax.swing.JTextField();
        etel = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ecole = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Apellido:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(304, 58, 50, 14);

        aux.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                auxKeyPressed(evt);
            }
        });
        getContentPane().add(aux);
        aux.setBounds(363, 55, 206, 20);

        tablaeliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tablaeliminar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tablaeliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaeliminarMouseClicked(evt);
            }
        });
        tablaeliminar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablaeliminarKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tablaeliminarKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(tablaeliminar);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(294, 95, 524, 253);

        busqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.jpg"))); // NOI18N
        busqueda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        busqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busquedaActionPerformed(evt);
            }
        });
        busqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                busquedaKeyPressed(evt);
            }
        });
        getContentPane().add(busqueda);
        busqueda.setBounds(570, 50, 30, 25);

        lista.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lista.setText("Listar");
        lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaActionPerformed(evt);
            }
        });
        getContentPane().add(lista);
        lista.setBounds(730, 50, 80, 23);

        jLabel7.setFont(new java.awt.Font("AR JULIAN", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 204));
        jLabel7.setText("Eliminar Medico:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(220, 10, 220, 28);

        enom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                enomKeyPressed(evt);
            }
        });
        getContentPane().add(enom);
        enom.setBounds(80, 140, 177, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Código:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 90, 50, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 132, 50, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Apellido:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 200, 50, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Dirección:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 260, 60, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Teléfono:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 320, 52, 10);

        eape.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                eapeKeyPressed(evt);
            }
        });
        getContentPane().add(eape);
        eape.setBounds(80, 200, 177, 20);

        edir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edirKeyPressed(evt);
            }
        });
        getContentPane().add(edir);
        edir.setBounds(80, 260, 177, 20);
        getContentPane().add(ecod);
        ecod.setBounds(80, 90, 177, 20);

        etel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                etelKeyPressed(evt);
            }
        });
        getContentPane().add(etel);
        etel.setBounds(80, 320, 175, 20);

        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Eliminar.jpg"))); // NOI18N
        btnEliminar.setText("Eiminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        btnEliminar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnEliminarKeyPressed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(150, 410, 100, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("No. Colegiado:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 375, 78, 14);
        getContentPane().add(ecole);
        ecole.setBounds(80, 370, 175, 20);

        btnVolver.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Regresar.jpg"))); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver);
        btnVolver.setBounds(60, 410, 90, 23);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salud5.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 860, 460);

        jButton2.setText("jButton2");
        jButton2.setFocusCycleRoot(true);
        getContentPane().add(jButton2);
        jButton2.setBounds(330, 390, 73, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaeliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaeliminarMouseClicked
   DefaultTableModel modelo = (DefaultTableModel) tablaeliminar.getModel();
       ecod.setText(modelo.getValueAt(tablaeliminar.getSelectedRow(),0)+""); 
       enom.setText(modelo.getValueAt(tablaeliminar.getSelectedRow(),1)+"");
        eape.setText(modelo.getValueAt(tablaeliminar.getSelectedRow(),2)+"");
        edir.setText(modelo.getValueAt(tablaeliminar.getSelectedRow(),3)+"");
        etel.setText(modelo.getValueAt(tablaeliminar.getSelectedRow(),4)+"");
        ecole.setText(modelo.getValueAt(tablaeliminar.getSelectedRow(), 5) + "");
        ecod.setEnabled(false);      
        ecole.setEnabled(false);
        Habilitar();
    }//GEN-LAST:event_tablaeliminarMouseClicked

    private void tablaeliminarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaeliminarKeyPressed

    }//GEN-LAST:event_tablaeliminarKeyPressed

    private void tablaeliminarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaeliminarKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaeliminarKeyTyped

    private void busquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedaActionPerformed
       Medico m = new Medico();
       m.BuscarMedico(aux.getText(), tablaEli);
       aux.requestFocus();
    }//GEN-LAST:event_busquedaActionPerformed

    private void listaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaActionPerformed
        Medico m = new Medico();
        Tabla t = new Tabla();
        t.LimpiarTabla(tablaEli);
        m.PresentarDatos(tablaEli);
    }//GEN-LAST:event_listaActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String codigo = ecod.getText();
        String apellido = eape.getText();
        String nombre = enom.getText();
        String direccion = edir.getText();
        String telefono = etel.getText();
        String colegiado = ecole.getText();
        if(codigo.length()==0||apellido.length()==0||nombre.length()==0||direccion.length()==0||telefono.length()==0||colegiado.length()==0)
        {
            JOptionPane.showMessageDialog(null, "Los registros no pueden estar vacios\nPor favor llene los registros", "Advertencia", JOptionPane.WARNING_MESSAGE);
            enom.requestFocus();
        }
        else
        {
            if(apellido.length()>50||nombre.length()>50||direccion.length()>50||telefono.length()>12||colegiado.length()>50)
            {
                JOptionPane.showMessageDialog(null, "El numero de caracteres en los registros es mayor al permitido\nNombre, Apellido, Direccion y Colegiado no pueden ser mayor a 50 caracteres\nTelefono no puede ser mayor a 12", "Advertencia", JOptionPane.WARNING_MESSAGE);
                enom.requestFocus();
            }
            else
            {
            int filasel;
            String id;
            filasel = tablaeliminar.getSelectedRow();
            if(filasel==-1)
            {
                JOptionPane.showMessageDialog(this, "Usted no ha seleccionado aún ninguna fila");
            }
            else
            {
                accion = 2;
                tablaEli = (DefaultTableModel) tablaeliminar.getModel();
                id = (String) tablaEli.getValueAt(filasel, 0); 
               Integer resp = JOptionPane.showConfirmDialog(this, "Esta a punto de eliminar los datos, \n\t¿desea continuar?", "Precaucion", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
               if(resp==0)
               {
                   Medico m = new Medico(eape.getText(), enom.getText(), edir.getText(), etel.getText(), ecole.getText());
                   Icon i = new ImageIcon(getClass().getResource("/Imagenes/Aceptar.jpg"));
                   JOptionPane.showMessageDialog(null, m.EliminarMedico(m, ecod.getText()),"Mensaje",JOptionPane.INFORMATION_MESSAGE, i);
                   Tabla t = new Tabla();
                   t.LimpiarTabla(tablaEli);
                   m.PresentarDatos(tablaEli);
                   ecod.setText("");
                   enom.setText("");
                   eape.setText("");
                   enom.setText("");
                   edir.setText("");
                   ecole.setText("");
                   etel.setText("");
                   aux.requestFocus();
               }
               else
               {
                   JOptionPane.showMessageDialog(this, "Datos sin eliminar");
               }
            }
        
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void auxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_auxKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            busqueda.requestFocus();
        }
    }//GEN-LAST:event_auxKeyPressed

    private void enomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enomKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            eape.requestFocus();
        }
    }//GEN-LAST:event_enomKeyPressed

    private void eapeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eapeKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            edir.requestFocus();
        }
    }//GEN-LAST:event_eapeKeyPressed

    private void edirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edirKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            etel.requestFocus();
        }
    }//GEN-LAST:event_edirKeyPressed

    private void etelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etelKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            btnEliminar.requestFocus();
        }
    }//GEN-LAST:event_etelKeyPressed

    private void btnEliminarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnEliminarKeyPressed
        // TODO add your handling code here:
        String codigo = ecod.getText();
        String apellido = eape.getText();
        String nombre = enom.getText();
        String direccion = edir.getText();
        String telefono = etel.getText();
        String colegiado = ecole.getText();
        if(codigo.length()==0||apellido.length()==0||nombre.length()==0||direccion.length()==0||telefono.length()==0||colegiado.length()==0)
        {
            JOptionPane.showMessageDialog(null, "Los registros no pueden estar vacios\nPor favor llene los registros", "Advertencia", JOptionPane.WARNING_MESSAGE);
            enom.requestFocus();
        }
        else
        {
            if(apellido.length()>50||nombre.length()>50||direccion.length()>50||telefono.length()>12||colegiado.length()>50)
            {
                JOptionPane.showMessageDialog(null, "El numero de caracteres en los registros es mayor al permitido\nNombre, Apellido, Direccion y Colegiado no pueden ser mayor a 50 caracteres\nTelefono no puede ser mayor a 12", "Advertencia", JOptionPane.WARNING_MESSAGE);
                enom.requestFocus();
            }
            else
            {
                Icon i = new ImageIcon(getClass().getResource("/Imagenes/Aceptar.jpg"));
                Medico m = new Medico(eape.getText(), enom.getText(), edir.getText(), etel.getText(), ecole.getText());
                JOptionPane.showMessageDialog(null, m.EliminarMedico(m, ecod.getText()),"Mensaje",JOptionPane.INFORMATION_MESSAGE, i);
                Tabla t = new Tabla();
                t.LimpiarTabla(tablaEli);
                m.PresentarDatos(tablaEli);
            }
        }
    }//GEN-LAST:event_btnEliminarKeyPressed

    private void busquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busquedaKeyPressed
        // TODO add your handling code here:
        String codigo = ecod.getText();
        String apellido = eape.getText();
        String nombre = enom.getText();
        String direccion = edir.getText();
        String telefono = etel.getText();
        String colegiado = ecole.getText();
        if(codigo.length()==0||apellido.length()==0||nombre.length()==0||direccion.length()==0||telefono.length()==0||colegiado.length()==0)
        {
            JOptionPane.showMessageDialog(null, "Los registros no pueden estar vacios\nPor favor llene los registros", "Advertencia", JOptionPane.WARNING_MESSAGE);
            enom.requestFocus();
        }
        else
        {
            if(apellido.length()>50||nombre.length()>50||direccion.length()>50||telefono.length()>12||colegiado.length()>50)
            {
                JOptionPane.showMessageDialog(null, "El numero de caracteres en los registros es mayor al permitido\nNombre, Apellido, Direccion y Colegiado no pueden ser mayor a 50 caracteres\nTelefono no puede ser mayor a 12", "Advertencia", JOptionPane.WARNING_MESSAGE);
                enom.requestFocus();
            }
            else
            {
                Icon i = new ImageIcon(getClass().getResource("/Imagenes/Aceptar.jpg"));
                Medico m = new Medico(eape.getText(), enom.getText(), edir.getText(), etel.getText(), ecole.getText());
                JOptionPane.showMessageDialog(null, m.EliminarMedico(m, ecod.getText()),"Mensaje",JOptionPane.INFORMATION_MESSAGE, i);
                Tabla t = new Tabla();
                t.LimpiarTabla(tablaEli);
                m.PresentarDatos(tablaEli);
            }
        }
    }//GEN-LAST:event_busquedaKeyPressed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDeliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDeliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDeliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDeliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDeliminar dialog = new JDeliminar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aux;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton busqueda;
    private javax.swing.JTextField eape;
    private javax.swing.JTextField ecod;
    private javax.swing.JTextField ecole;
    private javax.swing.JTextField edir;
    private javax.swing.JTextField enom;
    private javax.swing.JTextField etel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lista;
    private javax.swing.JTable tablaeliminar;
    // End of variables declaration//GEN-END:variables
}
